### PR TITLE
Add mail attribute to LDAP

### PR DESCRIPTION
**Pull request by csawyerYumaed**
Add a mail attribute to LDAP.

### CODE REVIEW

**Comment by csawyerYumaed** [comment]
well crap. I didn't mean to send ALL 3 commits.. but I'm fine with you including all 3, but the 3rd one (use http service) will probably not be useful for anyone but myself.

**Comment by LennardF1989** [comment]
Actually, your HTTP Service is exactly what I needed. I need a LDAP server that can pull his data from an external API, so it's perfect, thanks!

**Comment by johntdyer** [comment]
OMG, you made my f'ing day !  Thank you

**Comment by johntdyer** [comment]
@csawyerYumaed  any chance you have an example config showing how your branch is supposed to work?

**Comment by csawyerYumaed** [comment]
Sorry I've been on vacation.  You just specify it in the users config like so. and backend, it's just something like this:

But if your stuff doesn't return whatever my stuff does, then perhaps your HTTPS auth service won't work.

```
# The backend section controls the data store.
[backend]
  datastore = "config"
  baseDN = "dc=example,dc=com"
  #baseDN = ""
  home = "/home/"
  authURL = "https://auth.example.com/serviceAuth"

[[users]]
  name = "smcduck"
  unixid = 1045
  primarygroup = 1002
  passsha256 = "MAGIC SHA HERE"
  mail = "smcduck@example.com"
  displayName = "Spiffy McDuck"
```

**Comment by benyanke** [comment]
Closing this, feature now handled by #8.

**Comment by birlorg** [comment]
Mine was clearly a hack. cool!

**Pull request closed without merging**
